### ISSUE TITLE
Reducing .NET version

### ISSUE THREAD

**Issue by sergey-bastrakov** [Tulpep/Active-Directory-Object-Picker#21]
Hello,

Your library successfully build with 3.5 .Net framwork version. It is possible to reduce framework version in project settings to 3.5? There no reason to use 4.6.1. Or you can make several versions with different .Net framework.
Also can you specify restriction for .Net vesion in nuget package? Now I can install last package in 4.0 (for sample) project. And project is not building.

Thank you.

**Comment by ricardopolo** [comment]
@sergey-bastrakov @cmeuzelaar  I need your help for understanding what should I do here.

In #21 you ask to downgrade the .Net.
In #17  you as to upgrade it. 

So, how should we manage this? Do you know what is the best practice about versioning Nugets?

Thanks and regards

**Comment by MarcelGosselin** [comment]
I think we should target the lowest version of .NET on which it builds and runs succesfully. That way an application using the library can target any framework starting at that one. With current code, we force every user to use .NET 4.6.1 or more.
So go for .NET 3.5.
My 2¢

**Comment by HelOWeen** [comment]
@MarcelGosselin: Agreed, downgrading to the lowest possible .NET seems to be the sensible thing to do.

Especially since .NET 4.6.x is only included with the VS2017 (https://www.microsoft.com/net/targeting). Using it in its current form would force the distribution of .NET 4.6.1 along with the application.

**Comment by cmeuzelaar** [comment]
4.6.1 is available with 2015 (using it in my office), but I'd personally prefer a NuGet with a .NET 3.5 and a .NET 4.0 version since Windows 8+ do not ship with .NET 3.5 enabled by default. I have an example of how to do this to the project, but am incredibly unfamiliar with how to submit it to GitHub.

**Comment by ricardopolo** [comment]
All right, thank you everyone for your answers. Can anyone help me please with this?
In my machine (W10) the lowest available .NET is 4.

So a PR compiling with and older version of .Net will be happy merged! :)

**Comment by HelOWeen** [comment]
I cloned the project and tried a recompile with .NET 3.5 and 4.5, but I get an error complaining about the ActiveDS typelib. I've tried removing the project's reference and reinserting, but to no avail.  I'm on Windows 7 64-bit, so I guess I'm lacking the proper version of the TLB.
